baseURL = 'https://wouterjehee.com'
languageCode = 'en-us'
title = 'Wouter Jehee'

[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']

# TailwindCSS
[module]
    [module.hugoVersion]
        min = "0.128.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source       = "hugo_stats.json"
        target       = "assets/notwatching/hugo_stats.json"
        disableWatch = true
    [[module.mounts]]
        source       = "content"
        target       = "static"
        includeFiles = ["**/*.html"]
[build.buildStats]
    enable = true
[[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
[[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

[markup.asciidocExt]
  [markup.asciidocExt.attributes]
    experimental = ""
    source-highlighter = "rouge"

